[project]
name = "agentflow-ai"
version = "1.0.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "python-multipart",
    "python-dotenv",
    "langchain",
    "langchain-core",
    "langchain-community",
    "langchain-google-genai",
    "langchain-openrouter",
    "langgraph",
    "google-generativeai",
    "pypdf",
    "chromadb",
]

[tool.vercel]
entrypoint = "backend.main:app"